// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cQ8xFdjbfFP7Hm7wRaFseAY2kj06S3A',
    appId: '1:735407862893:web:c3699bdec47b337cd1bb64',
    messagingSenderId: '735407862893',
    projectId: 'fitness-80107',
    authDomain: 'fitness-80107.firebaseapp.com',
    storageBucket: 'fitness-80107.appspot.com',
    measurementId: 'G-LC88LYQLWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn4sgPPqiBwvbjDWzZbW3hjvpKUHgai2M',
    appId: '1:735407862893:android:3ae35c6487ad6266d1bb64',
    messagingSenderId: '735407862893',
    projectId: 'fitness-80107',
    storageBucket: 'fitness-80107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdPgIPNAaqKi8WKolukqGzV0WV9kB6TsE',
    appId: '1:735407862893:ios:a432bd2562b0e982d1bb64',
    messagingSenderId: '735407862893',
    projectId: 'fitness-80107',
    storageBucket: 'fitness-80107.appspot.com',
    iosClientId: '735407862893-4f42qak415cnu2msul3skq0nf65mrq9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnesstrackerapp',
  );
}
